/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavbar: typeof import('./src/components/bottom-navbar/BottomNavbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    Example: typeof import('./src/components/example/Example.vue')['default']
    Footer: typeof import('./src/components/footer-section/Footer.vue')['default']
    Header: typeof import('./src/components/header-section/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IconEpChatDotRound: typeof import('~icons/ep/chat-dot-round')['default']
    IconEpClock: typeof import('~icons/ep/clock')['default']
    IconEpDocument: typeof import('~icons/ep/document')['default']
    IconEpHouse: typeof import('~icons/ep/house')['default']
    IconEpMessage: typeof import('~icons/ep/message')['default']
    IconEpMinus: typeof import('~icons/ep/minus')['default']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    IconEpPosition: typeof import('~icons/ep/position')['default']
    IconEpSearch: typeof import('~icons/ep/search')['default']
    IconEpShoppingCart: typeof import('~icons/ep/shopping-cart')['default']
    IconEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IconEpUser: typeof import('~icons/ep/user')['default']
    LayoutWrapper: typeof import('./src/components/layout-wrapper/LayoutWrapper.vue')['default']
    ModalUserInfo: typeof import('./src/components/modal-user-info/ModalUserInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashScreen: typeof import('./src/components/splash-screen/SplashScreen.vue')['default']
  }
}
