/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavbar: typeof import('./src/components/bottom-navbar/BottomNavbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Example: typeof import('./src/components/example/Example.vue')['default']
    Footer: typeof import('./src/components/footer-section/Footer.vue')['default']
    Header: typeof import('./src/components/header-section/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IconEpChatDotRound: typeof import('~icons/ep/chat-dot-round')['default']
    IconEpClock: typeof import('~icons/ep/clock')['default']
    IconEpDocument: typeof import('~icons/ep/document')['default']
    IconEpHouse: typeof import('~icons/ep/house')['default']
    IconEpMessage: typeof import('~icons/ep/message')['default']
    IconEpMinus: typeof import('~icons/ep/minus')['default']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    IconEpPosition: typeof import('~icons/ep/position')['default']
    IconEpSearch: typeof import('~icons/ep/search')['default']
    IconEpShoppingCart: typeof import('~icons/ep/shopping-cart')['default']
    IconEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IconEpUser: typeof import('~icons/ep/user')['default']
    LayoutWrapper: typeof import('./src/components/layout-wrapper/LayoutWrapper.vue')['default']
    ModalUserInfo: typeof import('./src/components/modal-user-info/ModalUserInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashScreen: typeof import('./src/components/splash-screen/SplashScreen.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
