INSERT INTO menu_booth (
  booth_name,
  menu_name,
  price,
  description,
  tags,
  category,
  menu_type,
  spiciness_level,
  stock,
  is_favorite,
  estimated_minutes,
  created_by
)
VALUES
('Sambal Nusantara', 'Ayam Geprek Level 5', 18000, 'Ayam geprek super pedas dengan sambal khas Level 5', ARRAY['pedas', 'ayam', 'geprek'], 'makanan', 'umum', 1, 10, FALSE, 10, 'seed'),
('Sambal Nusantara', 'Ayam Geprek Original', 15000, 'Ayam geprek dengan sambal original tidak terlalu pedas', ARRAY['ayam', 'geprek'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Es Teh Segar', 'Es Teh Manis', 5000, 'Es teh manis segar pelepas dahaga', ARRAY['manis', 'teh', 'minuman'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Es Teh Segar', 'Lemon Tea', 7000, 'Teh dengan perasan lemon segar', ARRAY['manis', 'asam', 'teh'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Roti Bakar 88', 'Roti Bakar Coklat Keju', 12000, 'Roti bakar dengan isian coklat dan taburan keju', ARRAY['manis', 'coklat', 'keju'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Roti Bakar 88', 'Roti Bakar Kacang', 10000, 'Roti bakar dengan selai kacang gurih', ARRAY['manis', 'kacang'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Bakso Mantap', 'Bakso Urat Pedas', 20000, 'Bakso urat besar dengan kuah pedas menggoda', ARRAY['pedas', 'gurih', 'bakso'], 'makanan', 'umum', 1, 10, FALSE, 10, 'seed'),
('Bakso Mantap', 'Bakso Telur', 18000, 'Bakso isi telur rebus dengan kuah kaldu gurih', ARRAY['gurih', 'bakso', 'telur'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Sate Ayam Madura', 'Sate Ayam Bumbu Kacang', 18000, 'Sate ayam dengan bumbu kacang khas Madura', ARRAY['gurih', 'kacang', 'sate'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Sate Ayam Madura', 'Sate Ayam Pedas Manis', 19000, 'Sate ayam dengan saus pedas manis', ARRAY['pedas', 'manis', 'sate'], 'makanan', 'umum', 1, 10, FALSE, 10, 'seed'),
('Mie Ayam Lezat', 'Mie Ayam Bakso', 15000, 'Mie ayam dengan tambahan bakso kenyal', ARRAY['gurih', 'mie', 'bakso'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Mie Ayam Lezat', 'Mie Ayam Pedas', 16000, 'Mie ayam dengan sambal pedas menggugah selera', ARRAY['pedas', 'mie', 'ayam'], 'makanan', 'umum', 1, 10, FALSE, 10, 'seed'),
('Nasi Goreng 99', 'Nasi Goreng Spesial', 18000, 'Nasi goreng spesial dengan telur dan ayam suwir', ARRAY['gurih', 'nasi', 'ayam'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Nasi Goreng 99', 'Nasi Goreng Pedas Gila', 19000, 'Nasi goreng super pedas untuk pecinta cabai', ARRAY['pedas', 'nasi'], 'makanan', 'umum', 1, 10, FALSE, 10, 'seed'),
('Tahu Crispy', 'Tahu Crispy Gurih', 8000, 'Tahu goreng crispy dengan bumbu gurih', ARRAY['gurih', 'tahu'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Tahu Crispy', 'Tahu Pedas Manis', 9000, 'Tahu crispy dengan saus pedas manis', ARRAY['pedas', 'manis', 'tahu'], 'makanan', 'umum', 1, 10, FALSE, 10, 'seed'),
('Minuman Sehat', 'Jus Alpukat', 12000, 'Jus alpukat segar dan kental', ARRAY['manis', 'jus', 'alpukat'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Minuman Sehat', 'Jus Mangga', 10000, 'Jus mangga manis dan segar', ARRAY['manis', 'jus', 'mangga'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Gorengan Enak', 'Tempe Mendoan', 6000, 'Tempe mendoan tipis dan gurih', ARRAY['gurih', 'tempe'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Gorengan Enak', 'Bakwan Jagung', 6000, 'Bakwan jagung renyah dengan rasa manis jagung', ARRAY['manis', 'jagung', 'bakwan'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Dimsum Mantul', 'Dimsum Ayam', 10000, 'Dimsum isi ayam lembut dengan saus cocolan', ARRAY['gurih', 'ayam', 'dimsum'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Dimsum Mantul', 'Dimsum Udang', 12000, 'Dimsum isi udang segar', ARRAY['gurih', 'udang', 'dimsum'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Kopi Kekinian', 'Es Kopi Susu', 15000, 'Kopi susu kekinian dengan gula aren', ARRAY['manis', 'kopi', 'susu'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Kopi Kekinian', 'Kopi Hitam', 8000, 'Kopi hitam tanpa gula, kuat dan pahit', ARRAY['pahit', 'kopi'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Teh Herbal', 'Teh Jahe Hangat', 7000, 'Teh jahe untuk menghangatkan tubuh', ARRAY['hangat', 'jahe', 'teh'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Teh Herbal', 'Teh Serai', 7000, 'Teh dengan aroma serai segar', ARRAY['segar', 'teh', 'serai'], 'minuman', 'umum', 0, 10, FALSE, 10, 'seed'),
('Sosis Bakar', 'Sosis Bakar Original', 10000, 'Sosis bakar rasa original', ARRAY['gurih', 'sosis'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Sosis Bakar', 'Sosis Bakar Pedas', 11000, 'Sosis bakar dengan bumbu pedas menggoda', ARRAY['pedas', 'sosis'], 'makanan', 'umum', 1, 10, FALSE, 10, 'seed'),
('Martabak Mini', 'Martabak Manis Coklat', 10000, 'Martabak mini isi coklat manis', ARRAY['manis', 'coklat', 'martabak'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed'),
('Martabak Mini', 'Martabak Telur', 12000, 'Martabak mini isi telur dan daun bawang', ARRAY['gurih', 'telur', 'martabak'], 'makanan', 'umum', 0, 10, FALSE, 10, 'seed');
